### ISSUE TITLE
is their active development on the stack?

### ISSUE THREAD

**Issue by andyrutter90** [pauloborges/blessed#10]
Hi

I have just found your project and am very interested in cooperating if there is active development. I am also using the nrf51 chip and would be interested in extending the protocol coverage plus porting to other  chips.
## 

  Andy

**Comment by pauloborges** [comment]
Hi Andy.

First of all, thanks for your interest!

I was unable to work on blessed for several months. This condition may continue for a few more months. But I encourage you to contribute! I can review any code you write and possibly merge it.

**Comment by andyrutter90** [comment]
On 12/03/15 12:29, Paulo Borges wrote:

> Hi Andy.
> 
> First of all, thanks for your interest!
> 
> I was unable to work on blessed for a several months. This condition 
> may continue for a few more months. But I encourage you to contribute! 
> I can review any code you write and possibly merge it.

Hi Paulo

I will do that.

## 

```
 Andy
```

**Comment by pauloborges** [comment]
Great!

**Comment by AlexDaniel** [comment]
Indeed, this is so great. I really hope that someone will keep this project alive.
