### ISSUE TITLE
What kind of license would this stack have?

### ISSUE THREAD

**Issue by EarthLord** [pauloborges/blessed#5]
Hi Paulo,
Nice to see an open-source stack for BLE using nrf51822 as the hardware platform. I've worked on porting Contiki, a BSD clasuse-3 based IoT OS to this platform for my thesis. I am curious of the license that you want to release this work with.
Cheers,
Prithvi

**Comment by EarthLord** [comment]
Sorry, didn't see the license in the headers in the files. Finally, an open-source BLE stack being developed!

**Comment by pauloborges** [comment]
I've updated the readme file with license info.
