### ISSUE TITLE
Missing Makefile.config

### ISSUE THREAD

**Issue by VinceGa** [pauloborges/blessed#9]
in Makefile
-include Makefile.config

Please check it in.

**Comment by pauloborges** [comment]
You have to provide `Makefile.config` with your local settings. For example:

```
$ cat Makefile.config
PLATFORM=nrf51822
NRF51_SDK_PATH=/path/to/your/nrf51/sdk
```

**Comment by VinceGa** [comment]
Awesome. Thanks Paulo.
